# Generated by Django 4.2.11 on 2025-07-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Blog_text',
            new_name='blog_text',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
